// Generated by gencpp from file group1_roslab/scan_range.msg
// DO NOT EDIT!


#ifndef GROUP1_ROSLAB_MESSAGE_SCAN_RANGE_H
#define GROUP1_ROSLAB_MESSAGE_SCAN_RANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace group1_roslab
{
template <class ContainerAllocator>
struct scan_range_
{
  typedef scan_range_<ContainerAllocator> Type;

  scan_range_()
    : header()
    , max_v(0.0)
    , min_v(0.0)  {
    }
  scan_range_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , max_v(0.0)
    , min_v(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _max_v_type;
  _max_v_type max_v;

   typedef double _min_v_type;
  _min_v_type min_v;





  typedef boost::shared_ptr< ::group1_roslab::scan_range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::group1_roslab::scan_range_<ContainerAllocator> const> ConstPtr;

}; // struct scan_range_

typedef ::group1_roslab::scan_range_<std::allocator<void> > scan_range;

typedef boost::shared_ptr< ::group1_roslab::scan_range > scan_rangePtr;
typedef boost::shared_ptr< ::group1_roslab::scan_range const> scan_rangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::group1_roslab::scan_range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::group1_roslab::scan_range_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace group1_roslab

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'group1_roslab': ['/home/nvidia/group1_ws/src/group1_roslab/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::group1_roslab::scan_range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::group1_roslab::scan_range_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::group1_roslab::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::group1_roslab::scan_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::group1_roslab::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::group1_roslab::scan_range_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::group1_roslab::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f6032bf04499a2f200f7b14dd796c86";
  }

  static const char* value(const ::group1_roslab::scan_range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f6032bf04499a2fULL;
  static const uint64_t static_value2 = 0x200f7b14dd796c86ULL;
};

template<class ContainerAllocator>
struct DataType< ::group1_roslab::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "group1_roslab/scan_range";
  }

  static const char* value(const ::group1_roslab::scan_range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::group1_roslab::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 max_v\n\
float64 min_v\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::group1_roslab::scan_range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::group1_roslab::scan_range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.max_v);
      stream.next(m.min_v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct scan_range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::group1_roslab::scan_range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::group1_roslab::scan_range_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "max_v: ";
    Printer<double>::stream(s, indent + "  ", v.max_v);
    s << indent << "min_v: ";
    Printer<double>::stream(s, indent + "  ", v.min_v);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUP1_ROSLAB_MESSAGE_SCAN_RANGE_H
